# Enhanced Object Detection Configuration

# Car detection parameters - optimized for precision and recall
car_detection:
  # Clustering parameters
  clustering:
    eps: 0.5                 # Optimized epsilon for better car connectivity  
    min_points: 12           # Reduced for small/distant cars
    confidence_threshold: 0.50 # Balanced threshold for good precision/recall

  # Dimensional constraints (covers all vehicle types)
  dimensions:
    length_range: [2.5, 8.5]  # Compact cars to large trucks
    width_range: [1.2, 3.5]   # All vehicle widths
    height_range: [0.9, 3.2]  # Low sports cars to high trucks/SUVs
    volume_range: [3.5, 60.0] # Very wide volume range 
    aspect_ratio_range: [1.1, 5.5] # Very flexible aspect ratio

# General object detection
object_detection:
  # Downsampling parameters
  downsampling:
    target_points: 600000     # Further increased for maximum precision
    preserve_classes: ["car", "building", "pole", "traffic_sign"] # Preserve important classes during downsampling

  # Segmentation parameters
  segmentation:
    ground_removal_height: 0.15  # Height threshold for ground removal
    min_cluster_size: 15         # Minimum points for general objects
    max_cluster_distance: 0.5    # Maximum distance between points in a cluster

# Class-specific parameters - NO VEGETATION
class_parameters:
  car:
    color: [0, 0, 255]           # Blue for cars
    min_confidence: 0.6          # Minimum confidence score
  building:
    color: [70, 130, 180]        # Steel blue for buildings
    min_confidence: 0.5
  pole:
    color: [153, 153, 153]       # Gray for poles
    min_confidence: 0.5
  road:
    color: [128, 64, 128]        # Purple for roads
    min_confidence: 0.7
  sidewalk:
    color: [244, 35, 232]        # Pink for sidewalks
    min_confidence: 0.6
